docker run -it --privileged \
    -e DISPLAY=$DISPLAY \
    --env="QT_X11_NO_MITSHM=1" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /dev:/dev:rw \
    -v /home/kmk/2025-rbp/week4/lab03/ros2_ws:/home/user/ros2_ws \
    -v /home/kmk/2025-rbp/week4/lab03/ws:/home/user/ws \
    --env=LOCAL_USER_ID="$(id -u)" \
    --hostname $(hostname) \
    --network host \
    --name rbp mdeagewt/2025-rbp:lab02-assignment-answer bash
